version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  train:
    build: .
    command: python Wine_quality_model/train_pipeline.py
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

