app_config:
  package_name: "Wine_quality_model"
  training_data_file: "Wine_quality_model/datasets/train.csv"
  test_data_file: "Wine_quality_model/datasets/test.csv"
  pipeline_save_file: "best_random_forest"

model_config_params:
  target: "quality"
  features:
    - "fixed_acidity"
    - "volatile_acidity"
    - "citric_acid"
    - "residual_sugar"
    - "chlorides"
    - "free_sulfur_dioxide"
    - "total_sulfur_dioxide"
    - "density"
    - "pH"
    - "sulphates"
    - "alcohol"
  test_size: 0.2
  random_state: 42
  n_estimators:
    - 50
    - 100
  max_depth:
    - 10
    - 15















